name: 錯誤回報
description: 回報可重現的 hk-tick-collector 問題
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感謝回報。請先去敏（token / chat id / 私有位址）後再提交。

  - type: input
    id: version
    attributes:
      label: 專案版本 / Commit SHA
      placeholder: v0.1.0 或 a1b2c3d
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 問題摘要
      description: 一句話描述問題與影響。
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 重現步驟
      description: 逐步可執行命令。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 預期結果
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 實際結果
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 作業系統
      placeholder: Ubuntu 22.04 / macOS 15
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python 版本
      placeholder: 3.11.8
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 去敏後的關鍵 env
      placeholder: |
        FUTU_HOST=127.0.0.1
        FUTU_PORT=11111
        FUTU_SYMBOLS=HK.00700
        DATA_ROOT=/data/sqlite/HK
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 日誌片段（最近 10~30 分鐘）
      placeholder: |
        scripts/hk-tickctl logs --ops --since "20 minutes ago"
    validations:
      required: true
