name: 錯誤回報
description: 回報可重現的 hk-tick-collector 問題
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        感謝你回報問題。請先移除日誌與環境設定中的敏感資訊。

  - type: textarea
    id: summary
    attributes:
      label: 問題摘要
      description: 發生了什麼？你原本預期是什麼？
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 重現步驟
      description: 請提供可逐步執行的命令與設定。
      placeholder: |
        1. Configure ...
        2. Run ...
        3. Observe ...
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 作業系統
      placeholder: Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python 版本
      placeholder: 3.11.8
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 去敏後的 env 設定
      description: 請只提供與問題相關的 `.env` key（請移除 secrets）。
      placeholder: |
        FUTU_HOST=127.0.0.1
        FUTU_PORT=11111
        FUTU_SYMBOLS=HK.00700
        DATA_ROOT=/data/sqlite/HK
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 近期日誌（journalctl 節錄）
      description: 請附最近 10-30 分鐘輸出。
      placeholder: sudo journalctl -u hk-tick-collector --since "30 minutes ago" --no-pager
    validations:
      required: true

  - type: textarea
    id: db
    attributes:
      label: DB 診斷資訊
      description: 請附 DB 大小與 PRAGMA 輸出。
      placeholder: |
        sqlite3 "file:/data/sqlite/HK/20260211.db?mode=ro" "PRAGMA journal_mode; PRAGMA synchronous; PRAGMA wal_autocheckpoint;"
        ls -lh /data/sqlite/HK/20260211.db*
    validations:
      required: true
